package com.hamin.volumelock;

import android.app.Notification;
import android.app.NotificationChannel;
import android.app.NotificationManager;
import android.app.Service;
import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.content.IntentFilter;
import android.media.AudioManager;
import android.os.Build;
import android.os.Handler;
import android.os.IBinder;
import android.os.Looper;
import androidx.annotation.Nullable;
import androidx.core.app.NotificationCompat;

public class VolumeLockService extends Service {

    private static final int TARGET_VOLUME = 3;
        private static final String CHANNEL_ID = "volume_lock_channel";
            private static final int NOTIFICATION_ID = 1001;

                private AudioManager audioManager;
                    private Handler handler;
                        private Runnable volumeCheckRunnable;

                            private final BroadcastReceiver volumeChangeReceiver = new BroadcastReceiver() {
                                    @Override
                                            public void onReceive(Context context, Intent intent) {
                                                        String action = intent.getAction();
                                                                    if ("android.media.VOLUME_CHANGED_ACTION".equals(action)) {
                                                                                    int streamType = intent.getIntExtra("android.media.EXTRA_VOLUME_STREAM_TYPE", -1);
                                                                                                    if (streamType == AudioManager.STREAM_MUSIC) {
                                                                                                                        restoreVolume();
                                                                                                                                        }
                                                                                                                                                    }
                                                                                                                                                            }
                                                                                                                                                                };

                                                                                                                                                                    @Override
                                                                                                                                                                        public void onCreate() {
                                                                                                                                                                                super.onCreate();
                                                                                                                                                                                        audioManager = (AudioManager) getSystemService(Context.AUDIO_SERVICE);
                                                                                                                                                                                                handler = new Handler(Looper.getMainLooper());

                                                                                                                                                                                                        IntentFilter filter = new IntentFilter("android.media.VOLUME_CHANGED_ACTION");
                                                                                                                                                                                                                registerReceiver(volumeChangeReceiver, filter);

                                                                                                                                                                                                                        volumeCheckRunnable = new Runnable() {
                                                                                                                                                                                                                                    @Override
                                                                                                                                                                                                                                                public void run() {
                                                                                                                                                                                                                                                                restoreVolume();
                                                                                                                                                                                                                                                                                handler.postDelayed(this, 3000);
                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                                                                                            handler.post(volumeCheckRunnable);
                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                    @Override
                                                                                                                                                                                                                                                                                                                        public int onStartCommand(Intent intent, int flags, int startId) {
                                                                                                                                                                                                                                                                                                                                startForeground(NOTIFICATION_ID, buildNotification());
                                                                                                                                                                                                                                                                                                                                        restoreVolume();
                                                                                                                                                                                                                                                                                                                                                return START_STICKY;
                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                        private void restoreVolume() {
                                                                                                                                                                                                                                                                                                                                                                if (audioManager == null) return;
                                                                                                                                                                                                                                                                                                                                                                        int current = audioManager.getStreamVolume(AudioManager.STREAM_MUSIC);
                                                                                                                                                                                                                                                                                                                                                                                if (current != TARGET_VOLUME) {
                                                                                                                                                                                                                                                                                                                                                                                            audioManager.setStreamVolume(AudioManager.STREAM_MUSIC, TARGET_VOLUME, 0);
                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                            private Notification buildNotification() {
                                                                                                                                                                                                                                                                                                                                                                                                                    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                                                                                                                                                                                                                                                                                                                                                                                                                                NotificationChannel channel = new NotificationChannel(
                                                                                                                                                                                                                                                                                                                                                                                                                                                    CHANNEL_ID, "볼륨 고정 서비스",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        NotificationManager.IMPORTANCE_LOW);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    channel.setShowBadge(false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                NotificationManager nm = getSystemService(NotificationManager.class);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (nm != null) nm.createNotificationChannel(channel);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return new NotificationCompat.Builder(this, CHANNEL_ID)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .setContentTitle("볼륨 고정 실행 중")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .setContentText("미디어 볼륨 " + TARGET_VOLUME + " 고정됨")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .setSmallIcon(android.R.drawable.ic_lock_silent_mode_off)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .setPriority(NotificationCompat.PRIORITY_LOW)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .setOngoing(true)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .setAutoCancel(false)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .build();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    @Override
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        public void onDestroy() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                super.onDestroy();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        handler.removeCallbacks(volumeCheckRunnable);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                try { unregisterReceiver(volumeChangeReceiver); } catch (Exception ignored) {}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Intent restartIntent = new Intent(this, VolumeLockService.class);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            startForegroundService(restartIntent);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                startService(restartIntent);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                @Nullable
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    @Override
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        public IBinder onBind(Intent intent) { return null; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }